# Generated by Django 4.0.4 on 2022-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_veteranuser_zip_code'),
        ('event', '0002_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, to='user.veteranuser'),
        ),
    ]
