# Generated by Django 4.0.4 on 2022-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veteranuser',
            name='zip_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
